### PR TITLE
 [#191] fix for scaling up during recovery processing

### LINKED ISSUE #191: Pod which is scaled up during transaction recovery processing could not be fully activated
There could be a trouble with a pod which is asked for being scaled down. When it's in middle of the transaction recovery processing there are applied changes on annotations and labels. These are pointers used by transaction recovery processing to first deactivate the pod from the processing new requests (to finish only what is un-finished) second to annotate such pod with information on the stage of the recovery processing (the reconciliation happens several times and the process of recovery tries to start at place where it has finished).

When the WildFly application is asked to scale up again the pod in the middle of the recovery processing could not be cleaned from all the pointers.
The pod scaling down pod needs to be refreshed as a clean one when it's made active.

### PR DESCRIPTION
**Pull request by ochaloup**
fixes #191

### CODE REVIEW

File: pkg/controller/wildflyserver/wildflyserver_controller.go [hunk 1]
```diff
@@ -139,7 +139,7 @@ func (r *ReconcileWildFlyServer) Reconcile(request reconcile.Request) (reconcile
 	}
 
 	if ok, err := validate(wildflyServer); !ok {
-		return r.ManageError(wildflyServer, err)
+		return r.manageError(wildflyServer, err)
```
Comment (yersan) [inline pkg/controller/wildflyserver/wildflyserver_controller.go:142]: Thanks for this. The idea was to use this method from the outside by using a validation webhook, but sounds fine to reduce the scope now.

Comment (ochaloup) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:142]: Oh, I didn't know the context that the method should be used outside. I just checked where it's used and it made sense to me make it private. If you say I will change it back.

File: pkg/controller/wildflyserver/wildflyserver_controller.go [hunk 2]
```diff
@@ -279,12 +279,18 @@ func (r *ReconcileWildFlyServer) Reconcile(request reconcile.Request) (reconcile
...
 	if numberOfPodsToScaleDown <= 0 {
 		for k, v := range wildflyServer.Status.Pods {
-			if v.State != wildflyv1alpha1.PodStateActive {
+			if v.State != wildflyv1alpha1.PodStateActive { // was in scale down processing
 				wildflyServer.Status.Pods[k].State = wildflyv1alpha1.PodStateActive
 				updateWildflyServer = true
+				// the non-active pod may be in the middle of the scale down process, we need to completely refresh it
+				for _, podItem := range podList.Items {
+					if podItem.Name == v.Name {
+						resources.Delete(wildflyServer, r.client, &podItem)
```
[the remark this answers is not in the document]
Comment (ochaloup) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:291]: It's a good point just I think it's not appropriate to change the `podList` here. The list of pods are those which are known to `WildFlyServer` instance. That list is the same even the `Delete` is called. The delete only removes the `Pod` instance but `StatefulSet` immediately starts it back. The list of pod which is expected to be active for `WildFlyServer` remains unchanged. The `Delete` works as a way to restart/refrest the `Pod` instance setup - when recovery was in processing then the container setup was changed  - it could be in different ways depending what stage of the processing was hit by scale up.
Is the explanation of the purpose enough to have it as it is or did I miss some point here?

[the remark this answers is not in the document]
Comment (yersan) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:291]: Thank @ochaloup , we should be fine then.

I was thinking about the possibility when the `StatefulSet` immediately doesn't start the pod, in that case, the `WildFlyServer` status will continue using obsolete information, for example, the pod IP. If the pod is deleted, its IP will change. 

In any case, the `podList` is read again at the beginning of the reconcile loop, if the pending pod is not started yet, the loop will wait at the beginning, and once it is available the `podList` will contain the correct data, which means rest of the code will be using real information.

`WildFlyServer` status will be updated at the end of the loop with the correct information again. So, it would be a corner case where the `WildFlyServer` status could take more time to show the real information. It should not be a problem.

File: pkg/controller/wildflyserver/wildflyserver_controller.go (hunk 1 above)
Comment (yersan) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:142]: No, it is fine as it is, thanks!

**Review by yersan — APPROVED** [review]

File: pkg/controller/wildflyserver/wildflyserver_controller.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (ochaloup) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:291]: Yes, the WildFly server is always "eventually consistent" - e.g. pod could be just deleted manually by a user.

File: pkg/controller/wildflyserver/wildflyserver_controller.go (hunk 1 above)
Comment (ochaloup) [reply pkg/controller/wildflyserver/wildflyserver_controller.go:142]: Thanks.

**Comment by yersan** [comment]
Thank you @ochaloup
